[phases.setup]
nixPkgs = ['python39', 'chromium', 'chromedriver']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'python movie_alert.py --web-and-monitor'